<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>password</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>54e845fe-4f89-49c9-bd9e-795eab549db0</testSuiteGuid>
   <testCaseLink>
      <guid>b14c699a-7ebb-4df8-a3fe-dbd9f52943e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'secret_sauce'</defaultValue>
         <description></description>
         <id>a7fa7387-da10-4668-9e9f-8be3d7656104</id>
         <masked>false</masked>
         <name>password</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/TC02 - Failed Login with wrong password - Negative</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>718abec6-03b9-4f86-9ee3-b6fea83e809a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/password</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>718abec6-03b9-4f86-9ee3-b6fea83e809a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>a7fa7387-da10-4668-9e9f-8be3d7656104</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
